### ISSUE TITLE
.

### ISSUE THREAD

**Issue by lujiangz** [mustafaUrl/push_swap#1]
gelişmez

**Comment by mustafaUrl** [comment]
gelişti

**Comment by lujiangz** [comment]
3 priest nedir lan hee

**Comment by mustafaUrl** [comment]
wolf, i have a donkey, are you need?

**Comment by lujiangz** [comment]
TIŞ TIŞ
![maxresdefault](https://user-images.githubusercontent.com/31911561/193450199-53934a29-b547-478e-b00a-ac744daf359f.jpeg)
